### ISSUE TITLE
IndexError: tuple index out of range in visualize_attention due to unexpected attn_map shape

### ISSUE THREAD

**Issue by FakeWoke** [seilk/LocalizationHeads#6]
Hello, thanks for your great work.

When running the following command
`python localization_heads_finder.py stage=pipeline \
    image_file=./examples/images/bird.png \
    query="What is in this image?" \
    cache_dir=./checkpoints/llava-v1.5-7b \
    cache_dir_vision_tower=./checkpoints/clip-vit-large-patch14-336
`
I encountered the following error:
`IndexError: tuple index out of range
  File "localization_heads_finder.py", line 500, in visualize_attention
    P = int(np.sqrt(attn_map.shape[1] // 2))
`

The error comes form the following code in localization heads_finder.py:
``` 
def visualize_attention:
       ....
       # Plot attention maps
        offset = 1 if original_image else 0
        attn_gen_wise = attention_data[0]  # First generation step

        for i, head_info in enumerate(top_heads):
            l, h = head_info["layer"], head_info["head"]

            # Extract attention map
            attn_map = attn_gen_wise[l, 0, h]

            # Estimate patch size
            P = int(np.sqrt(attn_map.shape[1] // 2))

            # Focus on the last token's attention to image tokens
            last_token_idx = -1
            image_start_idx = 1  # Approximate position
            image_end_idx = image_start_idx + P*P  # Approximate position

            try:
                vis_attn = attn_map[last_token_idx, image_start_idx:image_end_idx].reshape(P, P)
            ......
```
  
The error seems to come from this line:
```
attn_map = attn_gen_wise[l, 0, h]
P = int(np.sqrt(attn_map.shape[1] // 2))
```
In my environment:
attention_data.shape == [32, 32, 1, 576]
So attn_gen_wise = attention_data[0] has shape [32, 1, 576]
Hence attn_map = attn_gen_wise[l, 0, h] returns a scalar with shape [1], causing the IndexError on attn_map.shape[1].

I changed the code to:
```
attn_map = attention_data[l, h, 0]   # now shape [576]
attn_map = np.reshape(attn_map, (1, -1))  # shape [1, 576]
P = int(np.sqrt(attn_map.shape[1] // 2))  # P = 16
```
it work.

But, I also noticed that later in the same function, attention is visualized like this:
`vis_attn = attn_map[last_token_idx, image_start_idx:image_end_idx].reshape(P, P)
`
Here, only P^2 = 256 tokens are visualized, while the full image token count is 576 (suggesting a 24x24 grid).
Why only visualize 256 tokens?
Shouldn’t it be something like `vis_attn = attn_map.reshape(24, 24)` to include all image tokens?

Thank you for this great project! I'd be happy to submit a PR if my proposed fix is correct.

**Comment by choidaedae** [comment]
I have same issue, waiting for fix..

**Comment by seilk** [comment]
Thank you for reporting the issue! The error has been fixed in #9 and merged into the main branch. I apologize for the delay due to conference commitments and other projects. Thanks again!

**Comment by choidaedae** [comment]
@seilk The error still occurs after pulling your commit. 

Specifically, in the line 493 of localization_heads_finder.py, the shape of attn_map is mismatched what we expected in line 500. 

```
for i, head_info in enumerate(top_heads):
            l, h = head_info["layer"], head_info["head"]

            # Extract attention map
            attn_map = attn_gen_wise[l, 0, h] << this shape is []. 

            # Estimate patch size
            P = int(np.sqrt(attn_map.shape[1]))

```

Could you please check your fix is working after fixing..?

**Comment by seilk** [comment]
Hey @choidaedae,
I have recently made modifications to the visualization code. Could you please verify if the updated code functions correctly? Note that the merged code may not work properly if the dimensions of the attention tensor stored in the _.pkl_ file do not conform to the expected shape `[L, H, 1, vis_len]`. (I assume you are already familiar with the meaning of each dimension in this tensor.) Please ensure that the tensor dimensions are validated before proceeding with the visualization task.
